---
- name: "Playbook that does nothing"
  hosts: "all"
  gather_facts: false

  tasks:
    - name: "Debug"
      delegate_to: "localhost"
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} was provisioned!"
